version: "2.1"
services:
  cassandra:
    image: cassandra:3.11.10
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  stwod:
    build:
      context: .
    depends_on:
      cassandra:
        condition: service_healthy
    network_mode: host
